### ISSUE TITLE
dockpulp as a library should not setup logger

### ISSUE THREAD

**Issue by pbabinca** [release-engineering/dockpulp#40] opened 2016-01-28 15:16 UTC
Basically 654db75f05c8f3197a7da55ad2603a10955d749f caused regression of https://github.com/release-engineering/dockpulp/issues/1

**Comment by TomasTomecek** [comment] 2016-01-29 10:08
Duplicate of #33 :p

**Closed** 2016-01-29 10:19 UTC
